#!/bin/bash

# Stop current Odoo Service
sudo service odoo-server stop
sudo su odoo && cd /odoo/odoo-server

# Update 1 module
./openerp-server -d $1 --update=$2

# Restart server
exit
sudo service odoo-server restart



